import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Block from './components/Block'
import IconGithub from './components/icons/IconGithub'
import IconLinkedin from './components/icons/IconLinkedin'
import IconEmail from './components/icons/IconEmail'
import IconTwitter from './components/icons/IconTwitter'
import IconInstagram from './components/icons/IconInstagram'

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-6xl mx-auto px-4 pt-4 md:pt-40">
        <div className="contenedor mb-4">
          <Block className="text-left md:text-right col-span-3 box-content Developing">
            <div className="text-5xl font-semibold pb-4 leading-tight">Developing software for 3 years</div>
          </Block>

          <div className="grid grid-cols-3 gap-4 Experience">
            <Block className="text-center flex justify-center flex-col">
              <div className="font-bold text-3xl">+3</div>
              <div className="text-xs">Years Experience</div>
            </Block>

            <Block className="text-center flex justify-center flex-col">
              <div className="font-bold text-3xl">+32</div>
              <div className="text-xs">Handled Project</div>
            </Block>

            <Block className="text-center flex justify-center flex-col">
              <div className="font-bold text-3xl">+53</div>
              <div className="text-xs">Clients</div>
            </Block>
          </div>

          <Block className="Networks flex justify-between items-center">
            <a href="https://github.com/rsolanodev" target="_blank">
              <IconGithub/>
            </a>
            <a href="https://www.linkedin.com/in/rsolanoweb/" target="_blank">
              <IconLinkedin/>
            </a>
            <a href="https://twitter.com/rsolanx" target="_blank">
              <IconTwitter/>
            </a>
            <a href="https://www.instagram.com/rsolano.dev/" target="_blank">
              <IconInstagram/>
            </a>
            <a href="mailto:rubensoljim@gmail.com" target="_blank">
              <IconEmail/>
            </a>
          </Block>

          <Block className="font-bold text-xl Header">@rsolano.dev</Block>

          <Block className="Details">
            <div className="flex justify-between">
              <ul>
                <li>Name</li>
                <li>Age</li>
                <li>Location</li>
                <li>Organization</li>
              </ul>
              <ul className="font-bold text-right">
                <li>Rubén Solano</li>
                <li>22</li>
                <li>Valencia, Spain</li>
                <li>Dekalabs</li>
              </ul>
            </div>
          </Block>

          <Block className="About">
            <div className="font-bold text-xl mb-2">About me 👨🏽‍💻</div>
            <div>
              ¡Hola! Me alegro mucho de verte por aquí, mi nombre es Rubén y soy ingeniero en software
              ubicado en Valencia, España. Desde que era pequeño siempre me ha interesado el software y 
              desde entonces he podido aprender de cada parte del software. Desde Diseño UI/UX, Frontend, 
              Backend, DevOps y actualmente IA.
            </div>
          </Block>

          <Image src="/me.png" alt="me" width={300} height={300} className={`${styles.box} Me h-full w-full`} />
        </div>

        <Block className="w-full">
          <div className="font-bold text-xl mb-4">Skills & Experience 🛠️</div>
          <div className="flex gap-8 flex-col md:flex-row">
            <div className="flex gap-4 shrink-0">
              <Image src="/dekalabs.png" alt="Dekalabs" width={48} height={48} className="w-12 h-12" />
              
              <div>
                <div className="font-bold text-md">Software Engineer</div>
                <div className="text-md">Dekalabs</div>
                <div className="text-xs">2019 - Present</div>
              </div>
            </div>

            <div>
              Dekalabs es una consultoría de desarrollo de software en remoto con sede en Valencia, ofrecen 
              soluciones a medida en tecnologías móviles nativas, webs, blockchain y machine learning. 
              En Dekalabs di mis primeros pasos como backend en 2019. 
            </div>
          </div>
        </Block>
      </main>
    </>
  )
}

export default Home;
