import Head from "next/head";
import Image from "next/image";
import Block from "@/components/Block";
import Age from "@/components/Age";

import {
  IconGithub,
  IconLinkedin,
  IconEmail,
  IconTwitter,
  IconInstagram,
} from "@/components/icons";

import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from "next-i18next";
import Experience from "@/components/Experiencie";

const Home = () => {
  const { t } = useTranslation();

  return (
    <>
      <Head>
        <title>{t("title")}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-6xl mx-auto px-4 pt-4 md:pt-20 pb-4">
        <div className="contenedor mb-4">
          <Block className="col-span-3 Developing flex gap-2 justify-center md:flex-col items-center font-semibold text-lg md:text-2xl">
            <div className="flex gap-6 text-center md:text-left">
              <span>☁️ {t("imagine")}</span>
              <span>🦄 {t("design")}</span>
            </div>
            <div className="flex gap-6 text-center md:text-left">
              <span>⚙️ {t("code")}</span>
              <span>🔁 {t("repeat")}</span>
            </div>
          </Block>

          <div className="grid grid-cols-3 gap-4 Experience">
            <Block className="text-center flex justify-center flex-col">
              <div className="font-bold text-3xl">+4</div>
              <div className="text-xs">{t("yearsExperience")}</div>
            </Block>

            <Block className="text-center flex justify-center flex-col">
              <div className="font-bold text-3xl">+32</div>
              <div className="text-xs">{t("projects")}</div>
            </Block>

            <Block className="text-center flex justify-center flex-col">
              <div className="font-bold text-3xl">+2757</div>
              <div className="text-xs">{t("contributions")}</div>
            </Block>
          </div>

          <Block className="Networks flex justify-between items-center">
            <a href="https://github.com/rsolanodev" target="_blank">
              <IconGithub />
            </a>
            <a href="https://www.linkedin.com/in/rsolanoweb/" target="_blank">
              <IconLinkedin />
            </a>
            <a href="https://twitter.com/rsolanx" target="_blank">
              <IconTwitter />
            </a>
            <a href="https://www.instagram.com/rsolano.dev/" target="_blank">
              <IconInstagram />
            </a>
            <a href="mailto:rubensoljim@gmail.com" target="_blank">
              <IconEmail />
            </a>
          </Block>

          <Block className="font-bold text-xl Header">@rsolano.dev</Block>

          <Block className="Details">
            <div className="flex justify-between">
              <ul>
                <li>{t("name")}</li>
                <li>{t("age")}</li>
                <li>{t("location")}</li>
                <li>{t("organization")}</li>
              </ul>
              <ul className="font-bold text-right">
                <li>Rubén Solano</li>
                <li>
                  <Age birthDate="2000-11-19" />
                </li>
                <li>{t("myLocation")}</li>
                <li>Dekalabs</li>
              </ul>
            </div>
          </Block>

          <Block className="About">
            <div className="font-bold text-xl mb-2">{t("aboutMe")}</div>
            <div>{t("myDescription")}</div>
          </Block>

          <Image
            src="/me.jpg"
            alt="me"
            width={300}
            height={300}
            className="Me h-full w-full object-cover rounded-2xl"
          />
        </div>

        <Block className="w-full">
          <div className="font-bold text-xl mb-4">
            {t("skillsAndExperience")}
          </div>
          <Experience />
        </Block>
      </main>
    </>
  );
};

export const getServerSideProps = async ({ locale }) => ({
  props: {
    ...(await serverSideTranslations(locale, ["common"])),
  },
});

export default Home;
