import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Block from "@/components/Block";

import {
  IconGithub,
  IconLinkedin,
  IconEmail,
  IconTwitter,
  IconInstagram,
} from "@/components/icons";

import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from "next-i18next";

const Home = () => {
  const { t } = useTranslation();

  return (
    <>
      <Head>
        <title>{t("title")}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-6xl mx-auto px-4 pt-4 md:pt-32">
        <div className="contenedor mb-4">
          <Block className="col-span-3 Developing flex justify-center md:flex-col items-center text-3xl md:text-4xl">
            <div className="font-semibold pr-2 md:pb-2 md:pr-0 px-4">
              {t("ad")}
            </div>
          </Block>

          <div className="grid grid-cols-3 gap-4 Experience">
            <Block className="text-center flex justify-center flex-col">
              <div className="font-bold text-3xl">+3</div>
              <div className="text-xs">Years Experience</div>
            </Block>

            <Block className="text-center flex justify-center flex-col">
              <div className="font-bold text-3xl">+32</div>
              <div className="text-xs">Handled Project</div>
            </Block>

            <Block className="text-center flex justify-center flex-col">
              <div className="font-bold text-3xl">+53</div>
              <div className="text-xs">Clients</div>
            </Block>
          </div>

          <Block className="Networks flex justify-between items-center">
            <a href="https://github.com/rsolanodev" target="_blank">
              <IconGithub />
            </a>
            <a href="https://www.linkedin.com/in/rsolanoweb/" target="_blank">
              <IconLinkedin />
            </a>
            <a href="https://twitter.com/rsolanx" target="_blank">
              <IconTwitter />
            </a>
            <a href="https://www.instagram.com/rsolano.dev/" target="_blank">
              <IconInstagram />
            </a>
            <a href="mailto:rubensoljim@gmail.com" target="_blank">
              <IconEmail />
            </a>
          </Block>

          <Block className="font-bold text-xl Header">@rsolano.dev</Block>

          <Block className="Details">
            <div className="flex justify-between">
              <ul>
                <li>{t("name")}</li>
                <li>{t("age")}</li>
                <li>{t("location")}</li>
                <li>{t("organization")}</li>
              </ul>
              <ul className="font-bold text-right">
                <li>Rubén Solano</li>
                <li>22</li>
                <li>{t("myLocation")}</li>
                <li>Dekalabs</li>
              </ul>
            </div>
          </Block>

          <Block className="About">
            <div className="font-bold text-xl mb-2">{t("aboutMe")}</div>
            <div>{t("myDescription")}</div>
          </Block>

          <Image
            src="/me.png"
            alt="me"
            width={300}
            height={300}
            className={`${styles.box} Me h-full w-full`}
          />
        </div>

        <Block className="w-full">
          <div className="font-bold text-xl mb-4">
            {t("skillsAndExperience")}
          </div>
          <div className="flex gap-8 flex-col md:flex-row">
            <div className="flex gap-4 shrink-0">
              <Image
                src="/dekalabs.png"
                alt="Dekalabs"
                width={48}
                height={48}
                className="w-12 h-12"
              />

              <div>
                <div className="font-bold text-md">Software Engineer</div>
                <div className="text-md">Dekalabs</div>
                <div className="text-xs">2019 - Present</div>
              </div>
            </div>

            <div>
              Dekalabs es una consultoría de desarrollo de software en remoto
              con sede en Valencia, ofrecen soluciones a medida en tecnologías
              móviles nativas, webs, blockchain y machine learning. En Dekalabs
              di mis primeros pasos como backend en 2019.
            </div>
          </div>
        </Block>
      </main>
    </>
  );
};

export const getServerSideProps = async ({ locale }) => ({
  props: {
    ...(await serverSideTranslations(locale, ["common"])),
  },
});

export default Home;
